# Generated by Django 4.1.2 on 2023-01-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="status",
        ),
        migrations.AddField(
            model_name="ticket",
            name="called",
            field=models.BooleanField(default=False),
        ),
    ]
