# Generated by Django 4.1.2 on 2023-01-03 01:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tickets", "0002_remove_ticket_status_ticket_called"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="superuser",
            name="user",
        ),
        migrations.RemoveField(
            model_name="waitingroom",
            name="staff",
        ),
        migrations.AddField(
            model_name="waitingroom",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name="Staff",
        ),
        migrations.DeleteModel(
            name="SuperUser",
        ),
    ]
